# Don't print a new line at the start of the prompt
add_newline = false

# Formating the prompt
format = """
[](bold 33)  $directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$time\
$status\
$character
"""

# $gcloud\ a

# Directory config
[directory]
truncation_length = 1
truncation_to_repo = false
read_only_style = "yellow"

# Replace the "❯" symbol in the prompt with "➜"
[character]                                 # The name of the module we are configuring is "character"
success_symbol = "|I|[➜](bold 10)"
error_symbol = "|E|[➜](bold 9)"
vicmd_symbol = "|V|[➜](bold 10)"

# AWS config
[aws]
symbol = "[ ](bold 208)"

# Disable the package, hiding it from the prompt completely
[package]
disable = true
